// Expense categories with Lucide icon names
export const EXPENSE_CATEGORIES = [
  { id: "an-uong", name: "Ăn uống", icon: "UtensilsCrossed", color: "#ef4444" },
  { id: "di-chuyen", name: "Di chuyển", icon: "Car", color: "#3b82f6" },
  { id: "mua-sam", name: "Mua sắm", icon: "ShoppingBag", color: "#8b5cf6" },
  { id: "giai-tri", name: "Giải trí", icon: "Gamepad2", color: "#f59e0b" },
  { id: "hoa-don", name: "Hóa đơn & Tiện ích", icon: "Zap", color: "#10b981" },
  { id: "suc-khoe", name: "Sức khỏe", icon: "Heart", color: "#f97316" },
  { id: "giao-duc", name: "Giáo dục", icon: "GraduationCap", color: "#6366f1" },
  { id: "du-lich", name: "Du lịch", icon: "Plane", color: "#14b8a6" },
  { id: "dich-vu", name: "Dịch vụ & Đăng ký", icon: "CreditCard", color: "#8b5cf6" },
  { id: "con-cai", name: "Con cái", icon: "Baby", color: "#f472b6" },
  { id: "gia-dinh", name: "Gia đình", icon: "Users", color: "#f43f5e" },
  { id: "khac", name: "Khác", icon: "MoreHorizontal", color: "#6b7280" },
] as const;

// Category lookup map for O(1) access
export const EXPENSE_CATEGORY_MAP = new Map(
  EXPENSE_CATEGORIES.map((cat) => [cat.name, cat] as const)
) as Map<string, (typeof EXPENSE_CATEGORIES)[number]>;

// Category keywords for AI parsing
export const EXPENSE_CATEGORY_KEYWORDS: Record<string, string[]> = {
  "Ăn uống": [
    "ăn",
    "uống",
    "cơm",
    "phở",
    "bún",
    "miến",
    "bánh",
    "chè",
    "trà",
    "cà phê",
    "nhà hàng",
    "quán",
    "buffet",
    "lẩu",
    "nướng",
    "chợ",
    "siêu thị",
    "thức ăn",
    "bữa sáng",
    "bữa trưa",
    "bữa tối",
    "bia",
    "rượu",
    "nước",
    "sữa",
    "kẹo",
    "snack",
    "fastfood",
    "mcdonald",
    "kfc",
    "lotteria",
    "pizza",
    "gà rán",
    "tạp hóa",
    "vinmart",
    "coopmart",
    "big c",
    "lotte mart",
  ],
  "Di chuyển": [
    "xe",
    "taxi",
    "grab",
    "uber",
    "be",
    "gojek",
    "xăng",
    "dầu",
    "xe máy",
    "ô tô",
    "xe bus",
    "xe khách",
    "tàu",
    "máy bay",
    "vé",
    "cước",
    "phí",
    "bảo dưỡng",
    "sửa chữa",
    "gửi xe",
    "đỗ xe",
    "cầu đường",
    "phí đường",
    "vietjet",
    "bamboo",
    "vietnam airline",
    "grab bike",
    "grab car",
    "xe ôm",
    "cyclo",
    "xích lô",
    "metro",
    "bus",
    "bến xe",
  ],
  "Mua sắm": [
    "mua",
    "shopping",
    "quần áo",
    "giày",
    "túi",
    "đồng hồ",
    "trang sức",
    "điện tử",
    "điện thoại",
    "laptop",
    "máy tính",
    "tv",
    "tivi",
    "nội thất",
    "đồ gia dụng",
    "mỹ phẩm",
    "chăm sóc",
    "mall",
    "trung tâm",
    "cửa hàng",
    "vincom",
    "aeon",
    "diamond plaza",
    "saigon centre",
    "takashimaya",
    "shopee",
    "lazada",
    "tiki",
    "sendo",
    "online",
    "ship",
    "giao hàng",
  ],
  "Giải trí": [
    "phim",
    "rạp",
    "cinema",
    "cgv",
    "lotte",
    "galaxy",
    "concert",
    "show",
    "ca nhạc",
    "karaoke",
    "bar",
    "pub",
    "club",
    "game",
    "net",
    "bi-a",
    "bowling",
    "massage",
    "spa",
    "gym",
    "thể thao",
    "bóng đá",
    "cầu lông",
    "bơi lội",
    "du lịch",
    "picnic",
    "cafe",
    "trà sữa",
    "bia ôm",
    "nhậu",
  ],
  "Hóa đơn & Tiện ích": [
    "điện",
    "nước",
    "gas",
    "internet",
    "wifi",
    "điện thoại",
    "truyền hình",
    "cáp",
    "viettel",
    "mobifone",
    "vinaphone",
    "vnpt",
    "fpt",
    "sài gòn tourist",
    "evn",
    "sawaco",
    "hóa đơn",
    "cước",
    "phí",
    "dịch vụ",
    "monthly",
    "hàng tháng",
    "nhà",
    "tiền nhà",
    "thuê nhà",
    "thuê phòng",
    "thuê trọ",
    "tiền trọ",
    "tiền phòng",
    "rent",
    "rental",
    "chủ nhà",
    "chủ trọ",
  ],
  "Sức khỏe": [
    "bác sĩ",
    "doctor",
    "bệnh viện",
    "phòng khám",
    "thuốc",
    "pharmacy",
    "nhà thuốc",
    "khám",
    "chữa",
    "răng",
    "nha khoa",
    "mắt",
    "tim",
    "xét nghiệm",
    "chích ngừa",
    "bảo hiểm",
    "y tế",
    "sức khỏe",
    "vitamin",
    "thuốc bổ",
    "massage",
    "spa",
    "vinmec",
    "fv",
    "ung bướu",
    "đa khoa",
    "chuyên khoa",
  ],
  "Giáo dục": [
    "học",
    "trường",
    "đại học",
    "cao đẳng",
    "trung học",
    "tiểu học",
    "mầm non",
    "học phí",
    "sách",
    "vở",
    "bút",
    "đồ dùng",
    "khóa học",
    "lớp",
    "gia sư",
    "tiếng anh",
    "toán",
    "văn",
    "lý",
    "hóa",
    "sinh",
    "sử",
    "địa",
    "ngoại ngữ",
    "kỹ năng",
    "chứng chỉ",
    "bằng cấp",
    "thi",
    "kiểm tra",
  ],
  "Du lịch": [
    "du lịch",
    "travel",
    "khách sạn",
    "hotel",
    "resort",
    "homestay",
    "airbnb",
    "vé máy bay",
    "tour",
    "guide",
    "hướng dẫn",
    "visa",
    "hộ chiếu",
    "vali",
    "đặt phòng",
    "booking",
    "agoda",
    "đà lạt",
    "nha trang",
    "phú quốc",
    "hạ long",
    "sapa",
    "hội an",
    "huế",
    "vũng tàu",
    "mũi né",
    "cần thơ",
  ],
  "Dịch vụ & Đăng ký": [
    "netflix",
    "spotify",
    "youtube",
    "facebook",
    "google",
    "apple",
    "microsoft",
    "office",
    "adobe",
    "zoom",
    "skype",
    "dropbox",
    "icloud",
    "drive",
    "đăng ký",
    "subscription",
    "monthly",
    "annual",
    "hàng tháng",
    "hàng năm",
    "premium",
    "pro",
    "plus",
    "membership",
    "thành viên",
    "gói cước",
  ],
  "Con cái": [
    "con",
    "cái",
    "bé",
    "trẻ em",
    "em bé",
    "sữa bột",
    "tã",
    "đồ chơi",
    "quần áo trẻ em",
    "sách thiếu nhi",
    "vaccin",
    "tiêm chủng",
    "khám bệnh cho bé",
    "học phí mầm non",
    "học phí",
    "đồ dùng học tập",
    "bánh kẹo",
    "sữa tươi",
    "váy bé gái",
    "quần bé trai",
    "giày trẻ em",
    "cặp sách",
    "xe đẩy",
    "nôi",
    "ghế ăn dặm",
    "bình sữa",
    "núm ty",
    "kem đánh răng trẻ em",
    "dầu tắm bé",
    "phấn rôm",
  ],
  "Gia đình": [
    "cha mẹ",
    "bố mẹ",
    "gia đình",
    "family support",
    "gửi tiền",
    "chuyển khoản",
    "ck",
    "support",
    "hỗ trợ",
    "chu cấp",
    "nuôi",
    "phụng dưỡng",
    "mẹ",
    "bố",
    "cha",
    "anh",
    "chị",
    "em",
    "vợ",
    "chồng",
    "con",
    "cháu",
    "ông",
    "bà",
  ],
  Khác: [
    "khác",
    "other",
    "misc",
    "linh tinh",
    "tạp",
    "phí",
    "fee",
    "charge",
    "thuế",
    "tax",
    "phạt",
    "fine",
    "tips",
    "bo",
    "từ thiện",
    "charity",
    "quà",
    "gift",
    "biếu",
    "tặng",
    "vay",
    "trả nợ",
    "lãi",
    "gửi tiết kiệm",
  ],
};

// Income categories with Lucide icon names
export const INCOME_CATEGORIES = [
  { id: "luong", name: "Lương", icon: "Banknote", color: "#22c55e" },
  { id: "thuong", name: "Thưởng", icon: "Gift", color: "#16a34a" },
  { id: "dau-tu", name: "Đầu tư", icon: "TrendingUp", color: "#15803d" },
  { id: "kinh-doanh", name: "Kinh doanh", icon: "Building2", color: "#059669" },
  { id: "freelance", name: "Freelance", icon: "Laptop", color: "#0d9488" },
  { id: "ban-hang", name: "Bán hàng", icon: "ShoppingCart", color: "#0891b2" },
  { id: "cho-thue", name: "Cho thuê", icon: "Home", color: "#0284c7" },
  { id: "lai-suat", name: "Lãi suất", icon: "PiggyBank", color: "#2563eb" },
  { id: "khac", name: "Khác", icon: "MoreHorizontal", color: "#6b7280" },
] as const;

// Category lookup map for O(1) access
export const INCOME_CATEGORY_MAP = new Map(
  INCOME_CATEGORIES.map((cat) => [cat.name, cat] as const)
) as Map<string, (typeof INCOME_CATEGORIES)[number]>;

export const INCOME_CATEGORY_KEYWORDS: Record<string, string[]> = {
  Lương: [
    "lương",
    "salary",
    "pay",
    "wage",
    "tiền lương",
    "phát lương",
    "monthly salary",
    "lương tháng",
    "lương cơ bản",
    "basic salary",
  ],
  Thưởng: [
    "thưởng",
    "bonus",
    "incentive",
    "commission",
    "hoa hồng",
    "thưởng tết",
    "thưởng cuối năm",
    "year end bonus",
    "quarterly bonus",
    "thưởng quý",
  ],
  "Đầu tư": [
    "đầu tư",
    "investment",
    "lãi cổ phiếu",
    "dividend",
    "stock profit",
    "crypto",
    "bitcoin",
    "forex",
    "fund",
    "mutual fund",
    "lãi suất",
    "interest",
  ],
  "Kinh doanh": [
    "kinh doanh",
    "business",
    "doanh thu",
    "revenue",
    "profit",
    "lợi nhuận",
    "buôn bán",
    "kiếm được",
    "thu về",
    "bán hàng",
  ],
  Freelance: [
    "freelance",
    "part time",
    "làm thêm",
    "side job",
    "consulting",
    "tư vấn",
    "project",
    "dự án",
    "contract",
    "hợp đồng",
    "remote work",
  ],
  "Bán hàng": [
    "bán",
    "sale",
    "sold",
    "bán hàng",
    "retail",
    "online selling",
    "shopee bán",
    "lazada bán",
    "facebook bán",
    "marketplace",
  ],
  "Cho thuê": [
    "cho thuê",
    "rent",
    "rental",
    "thuê nhà",
    "thuê phòng",
    "cho thuê xe",
    "airbnb",
    "homestay",
  ],
  "Lãi suất": [
    "lãi",
    "interest",
    "lãi suất",
    "ngân hàng",
    "tiết kiệm",
    "savings",
    "gửi tiết kiệm",
    "term deposit",
  ],
  Khác: [
    "khác",
    "other",
    "misc",
    "linh tinh",
    "tạp",
    "thu nhập",
    "thu nhập khác",
    "other income",
    "miscellaneous income",
    "refund",
    "hoàn tiền",
    "cashback",
    "reward",
    "prize",
  ],
};
